<!-- Header for navigations -->
<header>
  <div class="shown-menu">
    <nav>
      <ul class="navbar">
        <li>
          <a href="index.php">
            <img
              id="logo"
              src="images/smartglow_header.png"
              alt="SmartGlow Logo"
          /></a>
        </li>
        <li><a class="links" href="product.php">Product</a></li>
        <li><a class="links" href="enquire.php">Enquire</a></li>
        <li><a class="links" href="about.php">About</a></li>
        <li><a class="links" href="enhancements.php">Enhancements</a></li>
        <li><a class="links" href="enhancements2.php">Enhancements 2</a></li>
      </ul>
    </nav>
  </div>
  <!-- A hidden menu that shows when the media reaches 768px (tablet size) -->
  <nav class="hidden-menu">
    <ul class="dropdown">
      <li><a class="hidden-links" href="product.php">Product</a></li>
      <li><a class="hidden-links" href="enquire.php">Enquire</a></li>
      <li><a class="hidden-links" href="about.php">About</a></li>
      <li><a class="hidden-links" href="enhancements.php">Enhancements</a></li>
      <li>
        <a class="hidden-links" href="enhancements2.php">Enhancements 2</a>
      </li>
    </ul>
  </nav>
</header>
