<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description"
        content="Discover the latest smart lighting technology. Our smart light bulbs offer energy efficiency, remote control, and customizable lighting in every room in your house.">
    <meta name="keywords" content="smart light bulbs, smart lighting, smart home, remote control light">
    <meta name="author" content="Chong Yi Yang">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Light Bulb | SmartGlow</title>
    <!-- Icon beside title link -->
    <link rel="icon" href="images/smartglow.ico" type="image/x-icon">

    <!-- Link for CSS style sheet -->
    <link rel="stylesheet" href="styles/style.css">
    <script src="scripts/enhancements.js"></script>
</head>

<body>
    <!-- Include header and timer banner -->
    <?php
    include_once("header.inc");
    include_once("timer.inc");
    ?>

    <!-- Hero section to welcome user into the webpage -->
    <section id="home-hero-sec" class="hero-home">
        <div class="hero-content">
            <h1>Welcome to SmartGlow</h1>
            <p>Experience the Future of Lightning</p>
            <a id=shopbtn href="product.html">Shop Now</a>
        </div>
    </section>
    <!-- Features section to display features of SmartGlow -->
    <section id="feature-sec" class="features">
        <h2>Our Key Features</h2>
        <p>Everything you need to know about our product</p>
        <!-- Container to store cards -->
        <div class="feature-container">
            <div class="feature-card">
                <img src="images/energy_saving_icon.png" alt="Energy Saving">
                <h3>Energy Saving</h3>
                <p>Our efficient LED technology will help save on your energy bills</p>
            </div>
            <div class="feature-card">
                <img src="images/smart_control_icon.png" alt="Smart Controls">
                <h3>Smart Controls</h3>
                <p>Control our lights effortlessly using your smartphone or provided remote control</p>
            </div>
            <div class="feature-card">
                <img src="images/colors_icon.png" alt="Custom Colors">
                <h3>Customizable Colors</h3>
                <p>Choose from a wide range of colors to match your mood</p>
            </div>
        </div>
    </section>
    <!-- Explore section -->
    <section id="explore-section" class="explore">
        <!-- Explore text content -->
        <div class="explore-content">
            <h2> Explore Our SmartGlow Products </h2>
            <p> Discover the full potential of our SmartGlow range by exploring the interactive image.
                Hover over and click different areas of the image to learn about the unique designs of our smart
                lighting.</p>
        </div>
        <!-- Explore image map content -->
        <div class="explore-image">
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <img src="images/product_map.jpg" alt="Product Map" usemap="#image-map">

            <map name="image-map">
                <area alt="Smart Light Bulb" title="Smart Light Bulb" href="product.html#smart-light-bulb"
                    coords="8,185,17,215,30,219,31,438,35,437,36,220,68,222,82,222,89,197,70,187,53,184,53,173,46,172,45,183,27,181"
                    shape="poly">
                <area alt="Smart LED" title="Smart LED" href="product.html#smart-led-strips"
                    coords="154,149,140,153,130,163,123,180,123,204,134,226,145,240,161,248,182,249,196,241,207,223,208,206,206,183,193,165,178,152,166,149"
                    shape="poly">
                <area alt="Flexible Light Strip" title="Flexible Light Strip" href="product.html#smart-flexi-light"
                    coords="349,42,313,51,297,61,288,76,287,91,294,104,311,112,329,116,319,131,330,139,354,145,379,144,410,139,430,133,442,125,439,112,420,103,435,96,437,82,435,68,419,53,391,44"
                    shape="poly">
                <area alt="Smart LED" title="Smart LED" href="product.html#smart-led-strips"
                    coords="93,0,337,154,479,129,479,144,334,169,0,1" shape="poly">
            </map>
        </div>
    </section>

    <!-- Enquiry section -->
    <section class="enquiry">
        <h2>Have Any Questions?</h2>
        <p>We're here to help! Feel free to reach out for help if you have any questions.</p>
        <!-- Enquire now button with image -->
        <a id="enqbtn" href="enquire.html">
            <p>Enquire Now</p>
            <!-- SVG for arrow -->
            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 48 48">
                <path
                    d="M4,26h35.172l-6.586,6.586c-0.781,0.781-0.781,2.047,0,2.828C32.977,35.805,33.488,36,34,36s1.023-0.195,1.414-0.586l10-10 C45.789,25.04,46,24.531,46,24s-0.211-1.039-0.586-1.414l-10-10c-0.781-0.781-2.047-0.781-2.828,0 c-0.781,0.781-0.781,2.047,0,2.828L39.172,22H4c-1.104,0-2,0.896-2,2S2.896,26,4,26z">
                </path>
            </svg>
        </a>
    </section>

    <!-- Include footer using php -->
    <?php
    include_once("footer.inc");
    ?>


</body>


</html>